### ISSUE TITLE
Nice clone

### ISSUE THREAD

**Issue by cleanlock** [FredCodeFinally/AdblockForTwitch#1]
btw

**Comment by FredCodeFinally** [comment]
So you steal someones original extension source code. Then you DMCA someone who uses the same code from the original open source extension. You know full well it was opensource. Nice to know your intentions.

Contact form
Country of residence
India
Full legal name
Akshay ***
Company name
Twitch Adblock
Full legal name of the copyright holder you represent
Akshay ***
Contact email address
[alway***@gmail.com](mailto:alway***@gmail.com)
Identify and describe the copyrighted work
The copyrighted work includes the content which you can see on the webstore of the extension item. They have included the same content as we have in the webstore description. Then on the further inspection we found the extension source code itself is structured the same as we have. This copyrighted item is nothing but a replica made from the inspiration of our item. They have only changed the UI.
Where can we see an authorized example of the work?
https://chrome.google.com/webstore/detail/twitch-adblock/ljhnljhabgjcihjoihakgdiicdjncpkd
Allegedly infringing URLs
https://chrome.google.com/webstore/detail/adblock-for-twitch/doblogaebbpmpfpohfflgjfebejldofc/
I have a good faith belief that use of the copyrighted materials described above as allegedly infringing is not authorized by the copyright owner, its agent, or the law.
Please check to confirm
The information in this notification is accurate and I swear, under penalty of perjury, that I am the copyright owner or am authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
Please check to confirm
Signature
Akshay ***

**Comment by FredCodeFinally** [comment]
"The original author of this extension is "saucettv"" ...who did not give you permission to use the code.

**Comment by FredCodeFinally** [comment]
And if you would like to go further than that, then pixeltris is the one who made the original script. He's even contributing to your extension and you're DMCAing people for code that you didn't even touch.

**Comment by cleanlock** [comment]
I'm not DMCA'ing anyone lol. What are you talking about? Someone linked your GitHub on Discord and I just found it funny that you want to make money with someone else's code. I couldn't care less tbh. And I'm not from India, so it's not me.

**Comment by FredCodeFinally** [comment]
You're the one that is using someone elses code my dude...

**Comment by FredCodeFinally** [comment]
I can't accuse you of hacking my original accounts, so I won't. But you sure jumped up and took my code quick.

**Comment by FredCodeFinally** [comment]
So when you speak on "cloning", look at yourself.

**Comment by cleanlock** [comment]
Why the heck are you so butthurt? lmao. Relax dude.

I literally only said "nice clone btw" and that's it. What's your problem? You accuse me of DMAC'ing your extension. Why would I do that? I couldn't care less, as I told you already. Stop being so butthurt and childish, and move on dude. Grow up.

**Comment by FredCodeFinally** [comment]
I didn't need to give credit, it's my code. I'm annoyed because you linking the extension to your community and making out that it is bad, when actually it was the only one working, has now caused a DMCA takedown, of the working extension.

The DMCA notice has your extension, company name and sworn statements and happened to be an hour after you posted this, so I think it's fair for me to accuse you/Twitch Adblock of causing the DMCA takedown, as that is exactly what happened.

I'm annoyed that you decided to take my original 'sauce' code, after I had been hacked and ruined and then hypocritically called out a 'clone', when you did the exact same thing on actual copyrighted code. I remember a time when you considered adding a donate button, remember?

**Comment by FredCodeFinally** [comment]
You obviously do care about 'clones', otherwise this issue wouldn't exist would it, but you keep using other peoples code and resources, you do you.
